name: horizonlabs_exam
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  build_runner: ^2.2.0
  carousel_slider: ^4.1.1
  cupertino_icons: ^1.0.5
  custom_clippers: ^2.0.0
  dio: ^4.0.6

  drag_and_drop_lists:
    git:
      url: https://github.com/init-Mobile/DragAndDropLists
      ref: master

  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^1.0.4
  http: ^0.13.4
  intl: ^0.17.0
  mockito: ^5.2.0
  modal_bottom_sheet: ^2.1.0
  network_image_mock: ^2.1.1
  riverpod: ^1.0.3
  shared_preferences: ^2.0.15
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
    - test/data/
