name: horizonlabs_exam
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  intl: ^0.17.0
  dio: ^4.0.6
  flutter_riverpod: ^1.0.4
  riverpod: ^1.0.3
  carousel_slider: ^4.1.1
  animated_text_kit: ^4.2.2
  shared_preferences: ^2.0.15
  sticky_headers: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
